version: "3.8"

services:
  frontend:
    container_name: app_frontend
    build: ./Front
    volumes:
      - ./Front:/app
      - /app/node_modules
    ports:
      - 3001:3000
  backend:
    build: ./Back
    volumes:
      - ./Back:/app
      - /app/node_modules
    environment:
      NODE_ENV: dev
    ports:
      - 5001:3000
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
