version: "3.8"
services:
  npm:
    build: ./
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      NODE_ENV: dev
    ports:
      - 3000:3000
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: exampleDB
